name: moodtune_app
description: An app that analyzes playlists
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  bloc: ^9.0.0
  dartz: ^0.10.1
  dio: ^5.3.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.4
  go_router: ^12.1.3
  intl: ^0.20.2
  shadcn_ui: ^0.43.0
  url_launcher: ^6.2.2

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0

flutter:
  generate: true
  uses-material-design: true
