name: moodtune_app
description: An app that analyzes playlists
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  sentry_dio: ^9.10.0
  sentry_flutter: ^9.10.0
  talker_flutter: ^4.1.0
  talker_dio_logger: ^4.1.0
  app_links: ^6.2.0
  bloc: ^9.2.0
  cupertino_icons: ^1.0.8  
  dartz: ^0.10.1
  dio: ^5.3.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.4
  go_router: ^12.1.3
  intl: ^0.20.2
  shadcn_ui: ^0.43.0
  supabase_flutter: ^2.12.0
  url_launcher: ^6.2.2

dev_dependencies:
  sentry_dart_plugin: ^3.2.1
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0

flutter:
  generate: true
  uses-material-design: true

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  project: moodtune-app
  org: jordan-nnabugwu
